---
- hosts: esxi
  vars_prompt:
    - name: VMName
      private: no
    - name: Folder
      private: no
    - name: Template
      private: no
    - name: Datacenter
      private: no
    - name: Host
      private: no
    - name: User
      private: no
    - name: Password
      private: yes
  connection: local
  gather_facts: no
  tasks:
  - name: Create new VM
    vmware_guest:
      hostname: "{{ Host }}"
      username: "{{ User }}"
      password: "{{ Password }}"
      validate_certs: False
      name: "{{ VMName }}"
      template: "{{ Template }}"
      datacenter: "{{ Datacenter }}"
      folder: "{{ Folder }}"
      state: poweredon
      wait_for_ip_address: no