---
 - hosts: kf2
   become: true
   become_user: steam
   tasks:
    - name: Create steam DIR
      file:
        path: /tmp/steamcmd
        state: directory
        owner: steam
        mode: 0755

    - name: Download steamcmd
      unarchive:
        remote_src: yes
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /tmp/steamcmd

    - name: Change Owner of steamcmd
      file:
        dest: /tmp/steamcmd/
        owner: steam
        mode: 0755
        recurse: yes

    - name: Setup SteamCMD
      become_user: steam
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +quit

    - name: Install KillingFloor 2
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +force_install_dir ~/kf2 +app_update 232130 +quit

    - name: Install Server.cfg
      copy:
        src: "{{ item }}"
        dest: /home/steam/kf2/KFGame/Config/
        owner: steam
        group: steam
        mode: 0755
      with_fileglob:
          - "~/steamserver/configs/kf2/*.ini"

    - name: Install Scripts
      copy:
        src: ~/steamserver/scripts/kf2_start.sh
        dest: /home/steam/kf2/kf2_start.sh
        owner: steam
        group: steam
        mode: 0755