---
 - hosts: linux
   become: true
   tasks:
     - name: Reclaim SteamCMD Server
       file:
         path: /home/steam/{{ item }}
         state: absent
       with_items:
         - Steam
         - Squad
         - sandstorm-admin-wrapper
         - kf2
         - Valheim
     - name: Shutdown VM
       community.general.shutdown: