---
 - hosts: rs2
   become: true
   become_user: steam
   tasks:
    - name: Create steam DIR
      file:
        path: /tmp/steamcmd
        state: directory
        owner: steam
        mode: 0755

    - name: Download steamcmd
      unarchive:
        remote_src: yes
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /tmp/steamcmd

    - name: Change Owner of steamcmd
      file:
        dest: /tmp/steamcmd/
        owner: steam
        mode: 0755
        recurse: yes

    - name: Setup SteamCMD
      become_user: steam
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +quit

    - name: Install RisingStorm 2
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +force_install_dir ~/rs2 +app_update 418480 +quit