---
 - hosts: sandstorm
   become: true
   become_user: steam
   tasks:
     - name: Clone and install rbenv environment
       git:
         repo: 'git://github.com/sstephenson/rbenv.git'
         dest: /home/steam/.rbenv/

     - name: Clone ruby build
       git:
         repo: 'git://github.com/sstephenson/ruby-build.git'
         dest: /home/steam/.rbenv/plugins/ruby-build/

     - name: Install Bash_Profile
       copy:
         src: configs/sandstorm/.bash_profile
         dest: /home/steam/.bash_profile
         owner: steam
         group: steam
         mode: 0644

     - name: Source Profile
       shell:
         source /home/steam/.bash_profile

     - name: Install RUBY!
       shell:
         /home/steam/.rbenv/bin/rbenv install -v 2.6.3

     - name: Set Global Ruby
       shell:
         /home/steam/.rbenv/bin/rbenv global 2.6.3

     - name: Disable generating of documents
       copy:
         src: configs/sandstorm/.gemrc
         dest: /home/steam/.gemrc
         owner: steam
         group: steam
         mode: 0644

     - name: Install Gems
       shell:
         /home/steam/.rbenv/versions/2.6.3/bin/gem install bundler

     - name: Clone Admin Wrapper
       git:
         repo: 'https://github.com/Joe-Klauza/sandstorm-admin-wrapper.git'
         dest: '/home/steam/sandstorm-admin-wrapper'

     - name: Download steamcmd
       unarchive:
         remote_src: yes
         src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
         dest: /home/steam/sandstorm-admin-wrapper/steamcmd/installation

     - name: Change Owner of steamcmd
       file:
         dest: /home/steam/sandstorm-admin-wrapper/steamcmd/installation
         owner: steam
         mode: 0755
         recurse: yes

     - name: Setup SteamCMD
       shell: /home/steam/sandstorm-admin-wrapper/steamcmd/installation/steamcmd.sh +login anonymous +quit