---
 - hosts: linux*
   become: true
   tasks:
   - name: Setup New Steam User
     user:
       name: steam

 - hosts: linuxsteamcmd
   become: true
   tasks:

   - name: Install Libraries
     yum:
       name: "{{ packages }}"
     vars:
       packages:
        - glibc.i686
        - libstdc++.i686
        - screen
        - yum-cron
        - git-core
        - zlib
        - zlib-devel
        - gcc-c++
        - patch
        - readline
        - readline-devel
        - libyaml-devel
        - libffi-devel
        - openssl-devel
        - make
        - bzip2
        - autoconf
        - automake
        - libtool
        - bison
        - curl
        - sqlite-devel

   - name: Yum Update
     yum:
       name: '*'
       state: latest

   - name: Create steam DIR
     file:
      path: /tmp/steamcmd
      state: directory
      owner: steam
      mode: 0755

   - name: Download steamcmd
     unarchive:
       remote_src: yes
       src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
       dest: /tmp/steamcmd

   - name: Change Owner of steamcmd
     file:
       dest: /tmp/steamcmd/
       owner: steam
       mode: 0755
       recurse: yes

   - name: Setup SteamCMD
     become_user: steam
     shell: /tmp/steamcmd/steamcmd.sh +login anonymous +quit