---
 - hosts: linux*
   become: true
   tasks:
   - name: Setup New Steam User
     user:
       name: steam

   - name: Install Libraries
     yum:
       name: "{{ packages }}"
     vars:
       packages:
        - glibc.i686
        - libstdc++.i686
        - screen
        - git-core
        - zlib
        - zlib-devel
        - gcc-c++
        - patch
        - readline
        - readline-devel
        - libyaml-devel
        - libffi-devel
        - openssl-devel
        - make
        - bzip2
        - autoconf
        - automake
        - libtool
        - bison
        - curl
        - sqlite-devel

   - name: Yum Update
     yum:
       name: '*'
       state: latest