---
 - hosts: linux*
   become: true
   tasks:

   - name: Setup New Steam User
     user:
       name: steam

 - hosts: linuxsteamcmd
   become: true
   tasks:

   - name: Install Libraries
     yum:
        name=glibc.i686
        name=libstdc++.i686
        state=latest

   - name: Create steam DIR
     file:
      path: /home/steam/steamcmd
      state: directory
      owner: steam
      mode: 0755

   - name: Download steamcmd
     unarchive:
       remote_src: yes
       src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
       dest: /home/steam/steamcmd

   - name: Change Owner of steamcmd
     file:
       dest: /home/steam/steamcmd/
       owner: steam
       mode: 0755
       recurse: yes

   - name: Setup SteamCMD
     shell: /home/steam/steamcmd/steamcmd.sh +login anonymous +quit