---
 - hosts: valheim
   become: true
   become_user: steam
   tasks:
    - name: Create steam DIR
      file:
        path: /tmp/steamcmd
        state: directory
        owner: steam
        mode: 0755
    - name: Download steamcmd
      unarchive:
        remote_src: yes
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /tmp/steamcmd
    - name: Change Owner of steamcmd
      file:
        dest: /tmp/steamcmd/
        owner: steam
        mode: 0755
        recurse: yes
    - name: Setup SteamCMD
      become_user: steam
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +quit
    - name: Install Valheim
      shell: /tmp/steamcmd/steamcmd.sh +login anonymous +force_install_dir ~/Valheim +app_update 896660 +validate +quit
    - name: Download MODS!
      unarchive:
        remote_src: yes
        src: https://github.com/valheimPlus/ValheimPlus/releases/download/0.9/UnixServer.tar.gz
        dest: ~/Valheim