---
- hosts: esxi
  vars_prompt:
    - name: VMName
      private: no
    - name: Folder
      private: no
    - name: Template
      private: no
    - name: Host
      private: no
    - name: User
      private: no
    - name: Pass
      private: yes
  connection: local
  gather_facts: no
  tasks:
  - name: Clone GM to VM
    vmware_guest:
      hostname: "{{ Host }}"
      username: "{{ User }}"
      password: "{{ Pass }}"
      validate_certs: False
      name: "{{ VMName }}"
      template: "{{ Template }}"
      datacenter: s3cn3t
      folder: "{{ Folder }}"
      state: poweredon
      wait_for_ip_address: no